### ISSUE TITLE
Confusing Build Line

### ISSUE THREAD

**Issue by wtgee** [juliotux/astrometry-conda#1]
Hi @juliotux, thanks for the repo. Just looking over some of the scripts and was confused at the following expression, mostly by the oddly named directory that you are replacing. Should it really be `/opt/anaconda1anaconda2anaconda3`? I couldn't find anything in the anaconda docs about it although admittedly didn't look too long.

https://github.com/juliotux/astrometry-conda/blob/896e425251fa5b35440802a88c4697b5901856cb/netpbm/build.sh#L8

**Comment by juliotux** [comment]
This strange directory name is common in conda recipes. Even in [Continuum.io recipes](https://github.com/ContinuumIO/anaconda-recipes/blob/74fb2280662a022f2d12a7744b4823cfa5e236df/qt/qt.conf).

This netpbm recipe I adapted from [HCC recipes](https://github.com/unlhcc/hcc-conda-recipes) and it compile just fine to me. I think conda replace this path in the process.

**Comment by wtgee** [comment]
Got it, thanks!
