### ISSUE TITLE
Core Dump

### ISSUE THREAD

**Issue by wtgee** [juliotux/astrometry-conda#2]
I'm getting core dumps trying to run this. Will get more debug info later:

```
[1]    3382 illegal hardware instruction (core dumped)  solve-field /home/foo/images/temp/20181206T134737.cr2_g.fits
```

**Comment by sunyongyang** [comment]
hi, i have the same question:
lab30203@lab30203:~/syy$ sudo solve-field 712.jpg
Illegal instruction (core dumped)

**Comment by wtgee** [comment]
See also https://github.com/dstndstn/astrometry.net/issues/138

**Comment by sunyongyang** [comment]
thank you!

**Comment by sunyongyang** [comment]
yes

**Comment by sunyongyang** [comment]
hi, wtgee. 
What did you do in the end?

**Comment by wtgee** [comment]
> hi, wtgee.
> What did you do in the end?

I'm not using a conda version. Our latest app just runs on an updated ubuntu docker container and we just install from `apt`. Good luck!

**Comment by sunyongyang** [comment]
> > hi, wtgee.
> > What did you do in the end?
> 
> I'm not using a conda version. Our latest app just runs on an updated ubuntu docker container and we just install from `apt`. Good luck!

Thanks very much!

**Comment by juliotux** [comment]
Sorry for the late answer guys. This is very strange. I tested here, the netpbm is correctly installed, but it seems to do not be linked correctly. I will investigate this better.

**Comment by juliotux** [comment]
This seems to be a problem that affects a lot of libraries and is linked to the docker compilation in the conda-forge pipeline: https://github.com/conda/conda/issues/8373

In our case it seems to be linked to `gsl`/`openblas`: https://github.com/conda-forge/openblas-feedstock/issues/60 and there is not special to be done.

I'm seeking a solution. For temporary solution, you can build the package by yourselves using the https://github.com/conda-forge/astrometry-feedstock recipe. Just clone the repository and `./build-locally.py`. The package will be put `build_artifacts` directory.

**Comment by juliotux** [comment]
I'll close this bug here and move it to a better place. https://github.com/conda-forge/astrometry-feedstock/issues/10

@sunyongyang @wtgee could you debug the program with `gdb` and comment on the above issue?
